# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\sem7\Minor Project\UI\deepface\UI Files\studentloginfirstgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("background-color: rgb(219, 221, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 170, 271, 61))
        self.label.setStyleSheet("color: rgb(0, 85, 127);\n"
"font: 14pt \"Nirmala UI\";")
        self.label.setObjectName("label")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 20, 1281, 61))
        self.title.setStyleSheet("color: rgb(60, 25, 255);\n"
"qproperty-alignment: AlignCenter;\n"
"font: 95 16pt \"Nirmala UI\";")
        self.title.setObjectName("title")
        self.set_class = QtWidgets.QPushButton(self.centralwidget)
        self.set_class.setGeometry(QtCore.QRect(420, 350, 101, 31))
        self.set_class.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(52, 168, 83);")
        self.set_class.setObjectName("set_class")
        self.Check_Students = QtWidgets.QPushButton(self.centralwidget)
        self.Check_Students.setGeometry(QtCore.QRect(600, 350, 261, 31))
        self.Check_Students.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(123, 123, 184);")
        self.Check_Students.setObjectName("Check_Students")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 100, 271, 61))
        self.label_2.setStyleSheet("color: rgb(0, 85, 127);\n"
"font: 14pt \"Nirmala UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 250, 271, 61))
        self.label_3.setStyleSheet("color: rgb(0, 85, 127);\n"
"font: 14pt \"Nirmala UI\";")
        self.label_3.setObjectName("label_3")
        self.course_id = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.course_id.setGeometry(QtCore.QRect(630, 180, 221, 41))
        self.course_id.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.course_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.course_id.setObjectName("course_id")
        self.faculty_id = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.faculty_id.setGeometry(QtCore.QRect(630, 260, 221, 41))
        self.faculty_id.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.faculty_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.faculty_id.setObjectName("faculty_id")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Course Id</span></p></body></html>"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Hello Student Name</span></p></body></html>"))
        self.set_class.setText(_translate("MainWindow", "Join"))
        self.Check_Students.setText(_translate("MainWindow", "Check Attendance Report"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Join Class</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Faculty ID</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
