# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\sem7\Minor Project\UI\deepface\UI Files\teacherstudentreportgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("background-color: rgb(219, 221, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sheet = QtWidgets.QTableWidget(self.centralwidget)
        self.sheet.setGeometry(QtCore.QRect(390, 250, 521, 371))
        self.sheet.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Nirmala UI\";")
        self.sheet.setObjectName("sheet")
        self.sheet.setColumnCount(4)
        self.sheet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sheet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sheet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sheet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sheet.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 90, 141, 31))
        self.label.setStyleSheet("color: rgb(0, 85, 127);\n"
"font: 14pt \"Nirmala UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 140, 141, 31))
        self.label_2.setStyleSheet("color: rgb(0, 85, 127);\n"
"font: 14pt \"Nirmala UI\";")
        self.label_2.setObjectName("label_2")
        self.attendance = QtWidgets.QLabel(self.centralwidget)
        self.attendance.setGeometry(QtCore.QRect(530, 90, 281, 31))
        self.attendance.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.attendance.setObjectName("attendance")
        self.attention = QtWidgets.QLabel(self.centralwidget)
        self.attention.setGeometry(QtCore.QRect(530, 140, 281, 31))
        self.attention.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.attention.setObjectName("attention")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 20, 331, 41))
        self.label_3.setStyleSheet("color: rgb(60, 25, 255);\n"
"font: 16pt \"Nirmala UI\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 200, 1281, 41))
        self.label_4.setStyleSheet("color: rgb(60, 25, 255);\n"
"font: 16pt \"Nirmala UI\";")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.sheet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student Name"))
        item = self.sheet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Roll No"))
        item = self.sheet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Attendence"))
        item = self.sheet.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Attention"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Attendance</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Attention</span></p></body></html>"))
        self.attendance.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Attendance</span></p></body></html>"))
        self.attention.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Attention</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">OverAll Attendence Report</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Date wise Attendence Sheet</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
